version: '3.10'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: .
    depends_on:
      - backend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - BACKEND_URL=http://backend:5000
